name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: pip install -e .[Dev]
    - run: black --check *.py */
    - run: isort --check-only *.py */
    - run: flake8
    - run: mypy --install-types --non-interactive -p datatig
