name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install -e .[Dev]
    - run: py.test .
    # Test CLI code, which isn't tested in Python tests. Just check we can get some output.
    - run: python -m datatig build --sqliteoutput test1.sqlite tests/data/md_site/ && ls -al test1.sqlite
    - run: python -m datatig.cli build --sqliteoutput test2.sqlite tests/data/md_site/ && ls -al test2.sqlite

